version: "3"
volumes:
  apishtlink_db:
services:
  db:
    image: postgres:latest
    environment:
      PG_TRUST_LOCALNET: "true"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: shtlink
      POSTGRES_PASSWORD: shtlink
      POSTGRES_DB: shtlink
    volumes:
      - "apishtlink_db:/var/lib/postgresql/data"

  api:
    image: skymoore/shtl-ink-api:latest
    depends_on:
      - "db"
    environment:
      BASE_URL: http://api:8000
      ROOT_REDIRECT_URL: http://localhost:3000
      DB_HOST: db
      DB_NAME: shtlink
      DB_USER: shtlink
      DB_PASS: shtlink
    ports:
      - 127.0.0.1:8000:8000

  frontend:
    image: skymoore/shtl-ink:latest
    depends_on:
      - "api"
    volumes:
      - .env.docker:/opt/shtl_ink/.env.local
    ports:
      - 127.0.0.1:3000:3000